# Generated by Django 3.2.3 on 2021-05-25 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIEMsolution', '0003_car'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('discription', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='')),
                ('order', models.IntegerField(blank=True, null=True)),
                ('slug', models.SlugField(default='')),
            ],
        ),
        migrations.DeleteModel(
            name='Car',
        ),
    ]
